# Generated by Django 2.2.17 on 2021-01-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', models.IntegerField(max_length=12)),
                ('username', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('qualications', models.CharField(choices=[('G5', 'Grade5'), ('G1', 'Grade1'), ('G2', 'Grade2'), ('G4', 'Grade4'), ('G7', 'Grade7'), ('G9', 'Grade9'), ('G6', 'Grade6'), ('G8', 'Grade8'), ('G3', 'Grade3'), ('G10', 'Grade10')], max_length=2)),
            ],
        ),
    ]
