# Generated by Django 2.2.17 on 2021-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qualications',
            field=models.CharField(choices=[('G10', 'Grade10'), ('G4', 'Grade4'), ('G3', 'Grade3'), ('G7', 'Grade7'), ('G2', 'Grade2'), ('G8', 'Grade8'), ('G1', 'Grade1'), ('G6', 'Grade6'), ('G5', 'Grade5'), ('G9', 'Grade9')], max_length=2),
        ),
    ]
