# Generated by Django 2.2.17 on 2021-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210121_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_enum', models.IntegerField()),
                ('qualications', models.CharField(max_length=250)),
                ('teaching_exp', models.CharField(max_length=500)),
                ('about_me', models.TextField()),
                ('comments', models.TextField()),
            ],
            options={
                'db_table': 'usertype',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='qualications',
            field=models.CharField(choices=[('G4', 'Grade4'), ('G3', 'Grade3'), ('G5', 'Grade5'), ('G7', 'Grade7'), ('G8', 'Grade8'), ('G9', 'Grade9'), ('G10', 'Grade10'), ('G6', 'Grade6'), ('G1', 'Grade1'), ('G2', 'Grade2')], max_length=2),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
