# Generated by Django 2.2.17 on 2021-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210121_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qualications',
            field=models.CharField(choices=[('G3', 'Grade3'), ('G5', 'Grade5'), ('G10', 'Grade10'), ('G2', 'Grade2'), ('G4', 'Grade4'), ('G1', 'Grade1'), ('G6', 'Grade6'), ('G7', 'Grade7'), ('G9', 'Grade9'), ('G8', 'Grade8')], max_length=2),
        ),
    ]
