# Generated by Django 2.2.17 on 2021-01-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20210121_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qualications',
            field=models.CharField(blank=True, choices=[('G7', 'Grade7'), ('G5', 'Grade5'), ('G8', 'Grade8'), ('G10', 'Grade10'), ('G6', 'Grade6'), ('G1', 'Grade1'), ('G4', 'Grade4'), ('G9', 'Grade9'), ('G3', 'Grade3'), ('G2', 'Grade2')], max_length=8),
        ),
    ]
